[package]
name = "hypatia-core"
version = "0.1.0"
edition = "2021"
description = "A software-defined paradigm for next-generation AI and computation using Geometric Algebra"
authors = ["Ender <your-email@example.com>"]
license = "MIT"
repository = "https://github.com/mahreman/hypatia"
readme = "README.md"

[lib]
name = "hypatia_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
numpy = "0.21.0"

[dev-dependencies]

[[example]]
name = "rotation_demo"

[[example]]
name = "rotation3d_demo"